export const photos = [
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637773/cons/IMG_0267_zzpc5r.jpg",
    width: 3,
    height: 4,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637813/cons/IMG_9001_xsgsrk.jpg",
    width: 3,
    height: 4,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637810/cons/IMG_8995_vdroip.jpg",
    width: 4,
    height: 3,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637827/cons/IMG_9026_ofcvxn.jpg",
    width: 3,
    height: 4,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637829/cons/IMG_9028_e59mv2.jpg",
    width: 3,
    height: 4,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637824/cons/IMG_9008_oqnywc.jpg",
    width: 3,
    height: 4,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637815/cons/IMG_8996_xj9jza.jpg",
    width: 4,
    height: 3,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637792/cons/IMG_8968_dlugtb.jpg",
    width: 4,
    height: 3,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637785/cons/IMG_8959_mfcudc.jpg",
    width: 4,
    height: 3,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637773/cons/IMG_0267_zzpc5r.jpg",
    width: 3,
    height: 4,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637813/cons/IMG_9001_xsgsrk.jpg",
    width: 3,
    height: 4,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637810/cons/IMG_8995_vdroip.jpg",
    width: 4,
    height: 3,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637827/cons/IMG_9026_ofcvxn.jpg",
    width: 3,
    height: 4,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637829/cons/IMG_9028_e59mv2.jpg",
    width: 3,
    height: 4,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637824/cons/IMG_9008_oqnywc.jpg",
    width: 3,
    height: 4,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637815/cons/IMG_8996_xj9jza.jpg",
    width: 4,
    height: 3,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637792/cons/IMG_8968_dlugtb.jpg",
    width: 4,
    height: 3,
    alt: "people playing Moratia Card Quest Games",
  },
  {
    src: "https://res.cloudinary.com/dvbdefnwx/image/upload/v1666637785/cons/IMG_8959_mfcudc.jpg",
    width: 4,
    height: 3,
    alt: "people playing Moratia Card Quest Games",
  },
];